image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    
heroku:
 stage: deploy
 image: ruby:latest
 only:
 - master
 script:
 - dpl --provider=heroku --app=links-bio --api-key=$HEROKU_API_KEY

